# -*- coding: utf-8 -*-
"""Cybersecurity_Awareness_Page.html

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10_2lHHTQBs-uEegncpkhdITnd9XA4ZtX
"""

"""
Cybersecurity Awareness Project
Description: A Python program that teaches users how to spot phishing emails and scams.
Tech: Python

Introduction:
This program will help you recognize phishing emails and online scams.
Follow the instructions and answer the quiz questions to test your knowledge.

Tips for Spotting Phishing Emails:
- Check the sender's email address carefully.
- Look for spelling or grammar mistakes.
- Never click suspicious links.
- Verify requests for personal information.
- Be cautious with urgent or threatening messages.
"""

# Python code starts here
questions = [
    {"question": "You won a prize! Click here to claim. Safe? (yes/no): ", "answer": "no"},
    {"question": "Bank asks for your password. Safe? (yes/no): ", "answer": "no"},
]

score = 0
for q in questions:
    answer = input(q["question"]).strip().lower()
    if answer == q["answer"]:
        print("Correct!")
        score += 1
    else:
        print(f"Incorrect. Correct answer: {q['answer']}")
print(f"Your score: {score}/{len(questions)}")